const storeName = "Queen and Queen KABUKICHO｜新宿歌舞伎町 ニューハーフラウンジ";
const address = "東京都新宿区歌舞伎町2-14-8 メトロプラザ2 6F";
const mapUrl = "https://www.google.com/maps/search/?api=1&query=Queen%20and%20Queen%20KABUKICHO%20%E6%96%B0%E5%AE%BF%E6%AD%8C%E8%88%9E%E4%BC%8E%E7%94%BA";
const official = "https://vivalavida.co.jp/2026/01/19/ladyboy-lounge-queenqueen%E6%AD%8C%E8%88%9E%E4%BC%8E%E7%94%BA%E3%81%AB%E3%83%97%E3%83%AC%E3%82%AA%E3%83%BC%E3%83%97%E3%83%B3/";

const faq = [
  ["Queen and Queen KABUKICHOはどこにありますか？", `${address}にあります。`],
  ["営業時間は何時からですか？", "Googleビジネスプロフィールでは21:00開店と案内されています。営業状況は来店前にGoogleマップで最新情報をご確認ください。"],
  ["どのようなお店ですか？", "新宿・歌舞伎町にあるLADYBOY LOUNGE（ニューハーフラウンジ）です。"],
  ["最寄り駅はどこですか？", "東新宿駅、新宿三丁目駅、西武新宿駅、新宿駅から歌舞伎町方面へアクセスできます。経路はGoogleマップで現在地からご確認ください。"]
];
const relatedJa = ["Queen and Queen KABUKICHO","Queen and Queen 歌舞伎町","QUEEN&QUEEN 歌舞伎町","クイーンアンドクイーン歌舞伎町","新宿 ニューハーフラウンジ","歌舞伎町 ニューハーフラウンジ","新宿 LADYBOY LOUNGE","歌舞伎町 LADYBOY LOUNGE","新宿 ラウンジ","歌舞伎町 ラウンジ","歌舞伎町 バー","新宿 夜 ラウンジ","東新宿 ラウンジ","新宿三丁目 ラウンジ","西武新宿 ラウンジ","メトロプラザ2 ラウンジ","歌舞伎町2丁目 ラウンジ","新宿区歌舞伎町2-14-8","Queen and Queen アクセス","Queen and Queen 営業時間","Queen and Queen 地図","Queen and Queen 場所","Queen and Queen 住所","歌舞伎町 エンターテインメント","新宿 ナイトスポット","歌舞伎町 夜のお店","東京 LADYBOY LOUNGE","Kabukicho lounge","Shinjuku lounge","Tokyo ladyboy lounge"];
const relatedEn = ["Queen and Queen Kabukicho","Queen and Queen Shinjuku","Queen and Queen Tokyo","ladyboy lounge Kabukicho","ladyboy lounge Shinjuku","ladyboy lounge Tokyo","transgender lounge Shinjuku","Kabukicho nightlife lounge","Shinjuku nightlife","Tokyo nightlife lounge","lounge near Higashi Shinjuku Station","lounge near Seibu Shinjuku Station","lounge near Shinjuku Station","lounge near Shinjuku Sanchome Station","Kabukicho 2 chome lounge","Metro Plaza 2 Kabukicho","Queen and Queen address","Queen and Queen opening hours","Queen and Queen directions","Queen and Queen Google Maps","night lounge in Kabukicho","entertainment lounge Shinjuku","lounge bar Kabukicho","visit Queen and Queen Kabukicho","Tokyo LGBTQ entertainment","Kabukicho night destination","Shinjuku evening lounge","Queen and Queen location","how to get to Queen and Queen","lounge in Shinjuku Tokyo"];

export default function Page() {
  const schema = {"@context":"https://schema.org","@type":"BarOrPub",name:storeName,alternateName:["Queen and Queen KABUKICHO","LADYBOY LOUNGE QUEEN&QUEEN歌舞伎町"],url:"https://queen-and-queen-kabukicho.vercel.app",description:"新宿・歌舞伎町のLADYBOY LOUNGE（ニューハーフラウンジ）。",address:{"@type":"PostalAddress",streetAddress:"歌舞伎町2-14-8 メトロプラザ2 6F",addressLocality:"新宿区",addressRegion:"東京都",postalCode:"160-0021",addressCountry:"JP"},hasMap:mapUrl,sameAs:[official,mapUrl]};
  const faqSchema = {"@context":"https://schema.org","@type":"FAQPage",mainEntity:faq.map(([q,a])=>({"@type":"Question",name:q,acceptedAnswer:{"@type":"Answer",text:a}}))};
  return <><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(faqSchema)}}/>
    <header><a className="brand" href="#top">Q<span>&</span>Q</a><nav><a href="#about">特徴</a><a href="#info">店舗情報</a><a href="#access">アクセス</a><a href="#english">English</a></nav></header>
    <main id="top"><section className="hero"><div className="eyebrow">LADYBOY LOUNGE · KABUKICHO</div><h1>QUEEN<br/><i>and</i> QUEEN</h1><p className="lead">境界線のない美しさ。<br/>新宿・歌舞伎町で、新しい夜の幕が上がる。</p><a className="button" href={mapUrl} target="_blank" rel="noreferrer">Google Mapsで場所を見る</a><div className="scroll">SCROLL TO DISCOVER</div></section>
    <section id="about" className="section intro"><div><p className="kicker">ABOUT</p><h2>美しさに、<br/>境界線はいらない。</h2></div><div><p>{storeName}は、新宿・歌舞伎町にあるLADYBOY LOUNGEです。運営会社の公式発表が掲げるコンセプトは「境界線のない美しさ」。性別や既成概念を超えたエンターテインメントと、夜の一杯を楽しむための空間です。</p><p>メトロプラザ2の6階。歌舞伎町の夜へ向かう際は、最新の営業状況をGoogleマップで確認してからお越しください。</p></div></section>
    <section className="quote"><span>BEYOND</span><strong>BOUNDARIES</strong><p>QUEEN AND QUEEN · SHINJUKU KABUKICHO</p></section>
    <section id="info" className="section info"><p className="kicker">INFORMATION</p><h2>店舗情報</h2><dl><div><dt>正式店名</dt><dd>{storeName}</dd></div><div><dt>業態</dt><dd>LADYBOY LOUNGE／ニューハーフラウンジ</dd></div><div><dt>住所</dt><dd>{address}</dd></div><div><dt>営業時間</dt><dd>21:00〜<small>Googleビジネスプロフィール掲載情報。最新状況をご確認ください。</small></dd></div></dl></section>
    <section id="access" className="section access"><div><p className="kicker">ACCESS</p><h2>歌舞伎町の夜へ。</h2><p>{address}</p><p>東新宿駅、新宿三丁目駅、西武新宿駅、新宿駅から歌舞伎町方面へ。最適な経路は現在地からGoogleマップでご確認ください。</p><div className="actions"><a className="button" href={mapUrl} target="_blank" rel="noreferrer">ルートを表示</a><a className="textlink" href={official} target="_blank" rel="noreferrer">運営会社の公式発表 ↗</a></div></div><div className="mapcard"><span>35°41′42″ N</span><b>KABUKICHO</b><span>TOKYO · JAPAN</span></div></section>
    <section className="section faq"><p className="kicker">FAQ</p><h2>よくある質問</h2>{faq.map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</section>
    <section id="english" className="section english"><p className="kicker">ENGLISH GUIDE</p><h2>Queen and Queen<br/>KABUKICHO</h2><p>Queen and Queen KABUKICHO is a ladyboy lounge in Shinjuku&apos;s Kabukicho nightlife district. Its official concept is “beauty without boundaries,” presenting entertainment beyond gender and convention.</p><div className="enggrid"><p><b>Type</b><br/>Ladyboy lounge</p><p><b>Address</b><br/>Metro Plaza 2, 6F, 2-14-8 Kabukicho, Shinjuku-ku, Tokyo 160-0021, Japan</p><p><b>Opening</b><br/>From 9:00 PM, according to the Google Business Profile. Please check current details before visiting.</p><p><b>Directions</b><br/>Use Google Maps for a route from Higashi-Shinjuku, Shinjuku-sanchome, Seibu-Shinjuku, or Shinjuku Station.</p></div><a className="button" href={mapUrl} target="_blank" rel="noreferrer">OPEN GOOGLE MAPS</a></section>
    <section className="section related"><details><summary>関連する検索語 / Related searches</summary><div><p>{relatedJa.join("・")}</p><p>{relatedEn.join(" · ")}</p></div></details></section></main>
    <footer><div className="brand">Q<span>&</span>Q</div><p>{storeName}<br/>{address}</p><p>© 2026 Queen and Queen KABUKICHO</p></footer></>;
}
